import React from "react";

const Terms = () => {
  return (
    <div className="pt-16 px-2 py-4 md:px-32 ">
      <h1>Terms and Conditions of Use for PIXELAI</h1>
      <p>
        The following is a detailed description of the terms and conditions that
        apply to the use of the PIXELAI application ("the application"). Please
        read the following terms and conditions carefully before using the
        application. By using the application, you agree to these terms and
        conditions. If you do not agree to these terms and conditions, please do
        not use the application.
      </p>
      <h2>1. Use of the application</h2>
      <p>
        The PIXELAI application is an open-source application that uses
        artificial intelligence to generate images. The application allows the
        user to create images and share them in a feed. The application requires
        user authentication through Google or Facebook, but only access to
        email, profile picture, and username is granted.
      </p>
      <h2>2. Intellectual property</h2>
      <p>
        All images generated by the application are the property of the user who
        creates them. PIXELAI has no ownership rights over the created images.
        PIXELAI retains intellectual property rights over the source code of the
        application and any other intellectual property related to the
        application.
      </p>
      <h2>3. Limitations of liability</h2>
      <p>
        PIXELAI is not responsible for the images generated by the application.
        The user is solely responsible for the content of the images they create
        and share. PIXELAI will not be liable for any damages or losses caused
        by the use of the application.
      </p>
      <h2>4. Modifications to the application</h2>
      <p>
        PIXELAI reserves the right to modify the application at any time and
        without prior notice. Modifications may include adding or removing
        features or functionality, as well as changes to the terms and
        conditions.
      </p>
      <h2>5. Privacy</h2>
      <p>
        PIXELAI respects the user's privacy and is committed to protecting their
        personal information. The application only collects information
        necessary for user authentication and for the use of the application.
        The collected information will not be shared with third parties without
        the user's express consent.
      </p>
      <h2>6. Termination of account</h2>
      <p>
        PIXELAI reserves the right to terminate a user's account at any time and
        for any reason. In the event of account termination, the user will lose
        access to the application and all images generated by it.
      </p>
      <h2>7. Applicable law</h2>
      <p>
        These terms and conditions are governed by the laws of [country]. Any
        disputes arising in connection with these terms and conditions shall be
        resolved by the competent courts of [city].
      </p>
      <p>
        By using the PIXELAI application, the user agrees to the above terms and
        conditions. PIXELAI reserves the right to modify these terms and
        conditions at any time and without prior notice. Any changes to the
        terms and conditions will be effective immediately upon posting in the
        application. If the user does not agree with the modified terms and
        conditions, they must stop using the application.
      </p>
    </div>
  );
};

export default Terms;
