export const surpriseMePrompts = [
  "character portrait of an esoteric angel wearing robes, by peter mohrbacher, mark brooks, jim burns, marina abramovic, wadim kashin, greg rutkowski, trending on artstation",
  "symmetry!! portrait of aztez warrior, sci-fi armour, tech wear, glowing lights!! sci-fi, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha",
  "a cyberpunk cyborg killer ninja with a laser katana, hero pose, threatening, dark neon alley in the background, rain is falling, digital artwork trending on artstation, 4k",
  "insanely detailed. instagram photo, kodak portra. by wlop, ilya kuvshinov, krenz cushart, greg rutkowski, pixiv. zbrush sculpt, octane, maya, houdini, vfx. huge cityscape. cinematic dramatic atmosphere, sharp focus, volumetric lighting",
  "Gorgeous armor achaemenid persian warrior girl by ilya kuvshinov, krenz cushart, Greg Rutkowski, trending on artstation",
  "a cow in a luxury chair reading the newspaper, digital art, landscape, fantasy art, octane render, ureal engine, high detail, very realistic, by greg rutkowski. by james gurney",
  "anthropomorphic beer berserker, intricate, elegant, highly detailed animal monster, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha, 8k",
  "realistic 3d render of a cyberpunk android sneaker, beautiful studio lighting, soft, sharp focus, neon cyberpunk highlights, intricate detail, gold and red accents, soft rubber, octane render, side view, close up, trending on artstation, deviantart",
  "tekken king, contemporary collage, highly detailed, digital painting, 4k, hdr, punk, fashion, smooth, sharp focus, art by nick knight, sandra chevrier and john hoyland",
  "giant lovecraftian monster looms over a tiny party of 5 adventurers, high fantasy, horror, dnd, highly detailed, smooth, sharp focus, chiaroscuro, digital painting, artgerm and greg rutkowski and alphonse mucha",
  "3d fractal background by Escher, psychedelic!, mandelbulb 3d, digital art, high details!, depth of field!, hard lighting!, trending on artstation, deviantart, octane render, HD, 8k, eric zener, elson peter, zdzisław beksiński, vivid, artgerm",
  "highly realistic boy with curly brown hair and brown eyes, a wooden bow on his back, highly detailed and intricate, concept art illustration",
  "the bright light looking at you with a blured snapshot of the universe in the background from'lost in space ( 2018 ) ', soft muted flares on backside, frontal view, very long shot, cinematic light, realistic shaded lighting, futuristic, digital art, trending on artstation, golden ratio, perfect symmetrical, perfect intricate, masterpiece, hyperrealistic, octane render",
  "ultra realistic cg rendering of a lighthouse in a utopian futuristic city of flowers and stained glass by the sea. multi layered. key art. parametric design. organic. award winning. white chrome turquoise marble, summer sky, mirror, by hirofumi maruko and godwin akpan and yuliya zabelina and syd mead. photorealism. highly detailed, sharp focused details",
  "character portrait of an esoteric angel wearing robes, by peter mohrbacher, mark brooks, jim burns, marina abramovic, wadim kashin, greg rutkowski, trending on artstation",
  "victoria secret runway show, light, shadows, reflections, flowers, epic composition, intricate, elegant, volumetric lighting, digital painting, highly detailed, artstation, sharp focus, illustration, concept art, ruan jia, steve mccurry, artgerm and mina petrovic and timothy kong and marina federovna",
  "A minotaur wolf, full body, black and white, fantasy art, monster art, in the style of masami kurumada, illustration, epic, fantasy, intricate, hyper detailed, artstation, concept art, smooth, sharp focus, ray tracing",
  "highly detailed vfx portrait of nico robin by eiichiro oda, makoto shinkai, alphonse mucha, sharp focus, art by artgerm and greg rutkowski!, backlit, harsh overhead sunlight, blue eyes, aquiline nose, stanley kybric, kaoru mori, hyper detailed, smooth pixiv, fanbox",
  "portrait of a man with a jupiter head. intricate abstract. intricate artwork. by tooth wu, wlop, beeple, dan mumford. trending on artstation, greg rutkowski very coherent symmetrical artwork. cinematic, hyper realism, high detail, octane render, 8k, iridescent accents",
  "Beautiful anime painting of solarpunk summer chill day, by tim okamura, victor nizovtsev, greg rutkowski, noah bradley. trending on artstation, 8k, masterpiece, graffiti paint, fine detail, full of color, intricate detail, golden ratio illustration",
  "(((young girl))), ((skimpy clothes)),((exposed breast)), (teen), ((full body portrait)), fantasy, d & d, intricate ornate details, digital painting, ((pretty face)), concept art, sharp focus, illustration, art by artgerm greg rutkowski magali villeneuve, octane render Negative prompt: ((clothes))",
  "**poster of warrior princess| standing on hill | centered| key visual| intricate| highly detailed| breathtaking| precise lineart| vibrant| panoramic| cinematic| Carne Griffiths| Conrad Roset",
  "Portrait of {character} with {color} hair and with cute face, {background}, perfect composition, hyperrealistic, super detailed, 8k, high quality, trending art, trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski",
  "Full body Portrait of {goddess} with {pink} hair and with cute face, {bedroom}, full body, perfect composition, hyperrealistic, super detailed, 8k, high quality, trending art, trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski",
  "Anime Portrait of woman with red hair and with cute face, labyrinth, perfect composition, hyperrealistic, super detailed, 8k, high quality, trending art, trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski",
  "Portrait of {mushroom witch} with {pink} hair and with cute face, {apocalyptic background}, perfect composition, hyperrealistic, super detailed, 8k, high quality, trending art, trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski"
];

export const negativePrompts = [
  'no words', 'watermark', 'bad anatomy', 'deformed', ' cripple', ' ugly', ' additional arms', ' additional legs', ' additional head', ' two heads', ' multiple people', ' group of people', 'extra legs', ' extra arms', ' poorly drawn face', ' poorly drawn hands', ' poorly drawn feet', ' fat', ' disfigured', ' out of frame', ' long neck', ' poo art', ' bad hands', ' bad art', ' deformed', ' gun', ' double head', ' flowers', 'asian', 'hyperrealistic', 'child', ' blurry', ' fuzzy', ' extra legs', ' extra arms', ' extra fingers', ' poorly drawn hands', ' poorly drawn feet', ' disfigured', ' out of frame', ' tiling', ' bad art', ' deformed', ' mutated', ' double face', '3d', ' doll', ' octane', ' render', ' bad anatomy', ' blurry', ' extra arms', ' extra fingers', ' poorly drawn hands', ' disfigured', ' tiling', ' deformed', ' mutated'
] 